### ISSUE TITLE
Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

### ISSUE THREAD

**Issue by rubydev** [rubysamurai/purecss-sass#5]
Hello! When I bundle update, I'm getting this error:

<pre>Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811</pre>

**Comment by rubysamurai** [comment]
Hello,
Thanks for reporting this.

Currently Rails community can't decide on what would be the proper solution for Sass  deprecating its official Ruby implementation. Even fresh Rails app generated with latest Rails gem version is affected by this, since `rails-sass` depends on `sass` gem (related issues are [here](https://github.com/rails/sass-rails/issues/420) and [here](https://github.com/rails/rails/issues/32896)). 

The best long-term solution is to migrate from Rails asset pipeline to [Webpacker](https://github.com/rails/webpacker) (by the way, it will be default JavaScript compiler for Rails 6) and import `purecss` as Yarn dependency there.

**Comment by glebm** [comment]
It's fixed now, sass-rails uses libsass since v6.0.0. https://github.com/rails/sass-rails/releases/tag/v6.0.0

**Comment by rubysamurai** [comment]
@glebm thanks for the update!

Released new version with `sassc` dependency.
